version: '3.7'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql


  # api:
  #   image: node:latest
  #   ports:
  #     - '4000:4000'
  #   volumes:
  #     - ./api:/app
  #   working_dir: /app
  #   command: yarn start

  # client:
  #   image: nginx:latest
  #   ports:
  #     - '8080:80'
  #   volumes:
  #     - ./client/dist:/usr/share/nginx/html
  #     - ./default.conf:/etc/nginx/conf.d/default.conf
  #     - ./home/contenedores/volumen_nginx/certificate:/opt