version: '3.7'
services:
  api:
    image: node:latest
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
    working_dir: /app
    command: yarn start

  client:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./home/contenedores/volumen_nginx/certificate:/opt